INSULTS = ["I hope you forget your phone charger!",
           "May the chocolate chips in your cookies turn out to be raisins.",
           "May every sock you wear be slightly rotated just enough to be mildly uncomfortable.",
           "I'd like to leave you with one thought on your mind, but I don't think it would fit. ",
           "You look like someone who knows how to handle themselves in bed.",
           "I see that you’ve set aside this special time to humiliate yourself in public.",
           "You started at the bottom… and it’s been downhill ever since. ",
           "Brains aren’t everything. In fact in your case they’re nothing. ",
           " If what you don’t know can’t hurt you, you’re invulnerable. ",
           "You'll never be half the man your mother is."]